# Generated by Django 2.2 on 2020-01-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsigndev', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='status',
            field=models.CharField(choices=[('developpement', 'En développement'), ('refonte', 'Refonte du site'), ('production', 'En ligne'), ('projet', 'Projet')], max_length=100),
        ),
        migrations.AlterField(
            model_name='projet',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
