# Generated by Django 2.2 on 2020-01-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsigndev', '0002_auto_20200123_0829'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AlterField(
            model_name='projet',
            name='category',
            field=models.CharField(choices=[('Site vitrine', 'Site Vitrine'), ('Site Catalogue', 'Site Catalogue'), ('Blog', 'Site blog'), ('Site e-commerce', 'Site e-commerce')], max_length=100),
        ),
        migrations.AlterField(
            model_name='projet',
            name='status',
            field=models.CharField(choices=[('Projet', 'Projet'), ('Refonte du site', 'Refonte du site'), ('En ligne', 'En ligne'), ('En développement', 'En développement')], max_length=100),
        ),
    ]
